services:
  backend:
    image: ${IMAGE_URI}
    container_name: finnest-backend

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AES_SECRET_KEY: ${AES_SECRET_KEY}