name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'assignment/assignment-be/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: assignment/assignment-be

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG} \
            .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}

      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: assignment/assignment-be/docker-compose.yml
          target: /home/ec2-user/app/
          strip_components: 2

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_URI: ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          AES_SECRET_KEY: ${{ secrets.AES_SECRET_KEY }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_URI,AWS_REGION,DB_URL,DB_USERNAME,DB_PASSWORD,JWT_SECRET,AES_SECRET_KEY
          script: |
            set -e

            mkdir -p /home/ec2-user/app

            cat > /home/ec2-user/app/.env <<EOF
            IMAGE_URI=$IMAGE_URI
            DB_URL=$DB_URL
            DB_USERNAME=$DB_USERNAME
            DB_PASSWORD=$DB_PASSWORD
            JWT_SECRET=$JWT_SECRET
            AES_SECRET_KEY=$AES_SECRET_KEY
            EOF

            cd /home/ec2-user/app

            aws ecr get-login-password --region $AWS_REGION | \
              docker login \
              --username AWS \
              --password-stdin \
              592404497108.dkr.ecr.eu-north-1.amazonaws.com

            docker compose pull

            docker compose up -d --remove-orphans

            docker image prune -f

            docker ps