name: Deploy Finnest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-north-1

      ############################
      # FRONTEND
      ############################
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        working-directory: assignment-fe
        run: npm ci

      - name: Build frontend
        working-directory: assignment-fe
        env:
          VITE_API_URL: http://13.60.96.189:8080
        run: npm run build

      - name: Deploy frontend to S3
        run: aws s3 sync assignment-fe/dist/ s3://finnset-frontend-123 --delete

      ############################
      # BACKEND
      ############################
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build backend
        working-directory: assignment-be
        run: mvn clean package -DskipTests

      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Upload jar to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} "mkdir -p /home/ec2-user/app"

          scp -o StrictHostKeyChecking=no -i private_key.pem \
          assignment-be/target/*.jar \
          ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/app.jar

      - name: Restart backend
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }} '
            pkill -f "java -jar" || true
            nohup java -jar /home/ec2-user/app/app.jar > /home/ec2-user/app/app.log 2>&1 &
          '